package(default_visibility = ["//visibility:public"])

java_library(
    name = "camera",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//src/main/java/com/jagex/runescape/common",
    ],
)
