package(default_visibility = ["//visibility:public"])

java_library(
    name = "sound",
    srcs = glob([
        "*.java",
        "midi/*.java",
    ]),
    deps = [
        "//src/main/java/com/jagex/runescape/buffer",
        "//src/main/java/com/jagex/runescape/cache",
        "//src/main/java/com/jagex/runescape/common",
        "//src/main/java/com/jagex/runescape/node",
    ],
)
