package(default_visibility = ["//visibility:public"])

java_library(
    name = "common",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//src/main/java/com/jagex/runescape/node",
    ],
)
